from .models import additional_info
from .models import cron_job
from .models import address_info
from .models import education_info
from .models import extended_profile
from .models import family_info
from .models import financial_info
from .models import hr_contract_extended
from .models import language
from .models import military_info
from .models import nationality
from .models import personal_document
from .models import private_info
from .models import res_locality
from .models import resume_info
from .models import resume_line
from .models import shift_info
from .models import work_info